tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "htop"
brew "imagemagick"
brew "mas"
brew "nmap"
brew "nvm"
brew "streamlink"
brew "tree"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
cask "1password"
cask "airmail-beta"
cask "docker"
cask "dropbox"
cask "focus"
cask "gitkraken"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "keepingyouawake"
cask "kitematic"
cask "macdown"
cask "postman"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "sip"
cask "slack"
cask "spotify"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
mas "Airmail 3", id: 918858936
mas "Bear", id:1091189122
mas "Magnet", id: 441258766
mas "Paste", id: 967805235
