---
- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "{{ oh_my_zsh_install_dir }}"
  register: oh_my_zsh_dir

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ oh_my_zsh_install_dir }}"
    version: "{{ oh_my_zsh_version }}"
    depth: 1
  when: not oh_my_zsh_dir.stat.exists

- name: Install Oh My Zsh custom plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ oh_my_zsh_install_dir }}/custom/plugins/{{ item.name }}"
    version: "{{ item.version | default('HEAD') }}"
    depth: 1
  loop: "{{ oh_my_zsh_custom_plugins }}"
  loop_control:
    label: "{{ item.name }}"