- name: Ensure ~/.ssh exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"

- name: Install vaulted SSH private key
  ansible.builtin.copy:
    src: id_rsa.vault
    dest: "{{ ansible_facts['user_dir'] }}/.ssh/id_rsa"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0600"

- name: Copy public SSH key
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: "{{ ansible_facts['user_dir'] }}/.ssh/id_rsa.pub"
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0644"
