#!/usr/bin/env zsh

alias lc='colorls --gs --sd -lA'
alias lcc='colorls --gs --sd --tree'

# Folder shortcuts
alias dropbox='cd $HOME/Dropbox/'
alias gitbox='cd $HOME/Gitbox/'
alias agr5='cd $HOME/Gitbox/agr/agr5'
alias agr6='cd $HOME/Gitbox/agr/agr6'

# Server shortcuts
alias birkir.is='ssh -p 7773 birkir@178.62.38.116'
alias wp.is='ssh -p 7773 birkir@178.62.41.182'
alias agrvbox='ssh vboxadmin@192.168.101.15'

# Aliases from https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

# Get week number
alias week='date +%V'

# Update installed Ruby gems, npm, and their installed packages
# Use 'bubu' from brew plugin to update brew
alias npmu='npm install npm -g; npm update -g'
alias gemu='gem update --system; gem update; gem cleanup'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'