#!/usr/bin/env zsh

alias zshreload='source ~/.zshrc'

alias lc='colorls --gs --sd -lA'
alias lcc='colorls --gs --sd --tree'

alias f='open -a Finder ./' # Also aliased to 'ofd' from osx plugin

# List global npm installations
alias npmgL0='npm ls -g --depth=0'

# Folder shortcuts
alias dotfiles='cd $HOME/dotfiles/'
alias dropbox='cd $HOME/Dropbox/'
alias gitbox='cd $HOME/Gitbox/'         # Where I store downloaded github repos

# Git
alias glr='git submodule update --init --recursive'
# Git Remove Untracked Branches
alias gitru='git branch -r | awk "{print \$1}" | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk "{print \$1}" | xargs git branch -d'

# Python related
alias prp="pipenv run python"

# Aliases from https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

# Get week number
alias week='date +%V'

# Update installed Ruby gems, npm, and their installed packages
# Use 'bubu' from brew plugin to update brew
alias npmu='npm install npm -g; npm update -g'
alias gemu='gem update --system; gem update; gem cleanup'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy="/usr/libexec/PlistBuddy"

# Airport CLI alias
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Streams
alias tv='alias | grep streamlink | grep -o ".*=" | cut -d= -f1'
alias ruv='streamlink https://www.ruv.is/ruv best'
alias ruv2='streamlink https://www.ruv.is/ruv2 best'
alias svt1='streamlink https://www.svtplay.se/kanaler/svt1'
alias svt2='streamlink https://www.svtplay.se/kanaler/svt2'
alias dr1='streamlink https://www.dr.dk/tv/live/dr1'
alias dr2='streamlink https://www.dr.dk/tv/live/dr2'
alias dr3='streamlink https://www.dr.dk/tv/live/dr3'
alias bloomberg='streamlink https://www.bloomberg.com/live/europe best'
alias aljazeera='streamlink https://www.aljazeera.com/live/ best'

# Radio
alias radio='alias | grep Idummy | grep -o ".*=" | cut -d= -f1'
alias 101='vlc -Idummy https://stream.101.live/audio/101/chunklist.m3u8'
alias 80sbylgjan='vlc -Idummy http://icecast.365net.is:8000/orb80s.aac'
alias apparatid='vlc -Idummy http://icecast.365net.is:8000/orbApparatid.aac'
alias attan='vlc -Idummy http://89.17.150.20:443/attan'
alias bbcworld='vlc -Idummy http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk'
alias bylgjan='vlc -Idummy http://icecast.365net.is:8000/orbbylgjan.aac'
alias fb60='vlc -Idummy http://89.17.150.20:443/60flashback'
alias fb70='vlc -Idummy http://89.17.150.20:443/70flashback'
alias fb80='vlc -Idummy http://89.17.150.20:443/80flashback'
alias fb90='vlc -Idummy http://89.17.150.20:443/90flashback'
alias flashback='vlc -Idummy http://89.17.150.20:443/flashback'
alias fm957='vlc -Idummy http://icecast.365net.is:8000/orbFm957.aac'
alias fmextra='vlc -Idummy http://icecast.365net.is:8000/orbFmExtra.aac'
alias fmx='vlc -Idummy http://icecast.365net.is:8000/orbFMX.aac'
alias gullbylgjan='vlc -Idummy http://icecast.365net.is:8000/orbGullBylgjan.aac'
alias kaninn='vlc -Idummy http://89.17.150.20:443/kaninnmobile'
alias kissfm='vlc -Idummy http://89.17.150.20:443/kissfm'
alias lettbylgjan='vlc -Idummy http://icecast.365net.is:8000/orbLettBylgjan.aac'
alias ras1='vlc -Idummy http://netradio.ruv.is/ras1.mp3'
alias ras2='vlc -Idummy http://netradio.ruv.is/ras2.mp3'
alias retrofm='vlc -Idummy http://89.17.150.20:443/retromobile'
alias rondo='vlc -Idummy http://netradio.ruv.is/rondo.mp3'
alias ruvnull='vlc -Idummy http://netradio.ruv.is/ruvnull.mp3'
alias xid='vlc -Idummy http://icecast.365net.is:8000/orbXid.aac'



# Aliases from https://gist.github.com/natelandau/10654137

alias c='clear'                            # c:            Clear terminal display
mcd () { mkdir -p "$1" && cd "$1"; }       # mcd:          Makes new Dir and jumps inside
trash () { command mv "$@" ~/.Trash ; }    # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }   # ql:           Opens any file in MacOS Quicklook Preview
alias DT='tee ~/Desktop/terminalOut.txt'   # DT:           Pipe content to file on MacOS Desktop

#   -------------------------------
#   3.  FILE AND FOLDER MANAGEMENT
#   -------------------------------

zipf () { zip -r "$1".zip "$1" ; }          # zipf:         To create a ZIP archive of a folder
alias numFiles='echo $(ls -1 | wc -l)'      # numFiles:     Count of non-hidden files in current dir
alias make1mb='mkfile 1m ./1MB.dat'         # make1mb:      Creates a file of 1mb size (all zeros)
alias make5mb='mkfile 5m ./5MB.dat'         # make5mb:      Creates a file of 5mb size (all zeros)
alias make10mb='mkfile 10m ./10MB.dat'      # make10mb:     Creates a file of 10mb size (all zeros)

#   ---------------------------
#   4.  SEARCHING
#   ---------------------------

ffs () { /usr/bin/find . -name "$@"'*' ; }  # ffs:      Find file whose name starts with a given string
ffe () { /usr/bin/find . -name '*'"$@" ; }  # ffe:      Find file whose name ends with a given string


#   ---------------------------
#   6.  NETWORKING
#   ---------------------------

# alias myip='curl ip.appspot.com'                    # myip:         Public facing IP Address
alias netCons='lsof -i'                             # netCons:      Show all open TCP/IP sockets
alias flushDNS='dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs

# From https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Flush Directory Service cache
alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;echo "✌️ DNS flushed"'

#   ii:  display useful host related informaton
#   -------------------------------------------------------------------
ii() {
  print -P "\nYou are logged on $FG[003]$HOST"
  print -P "\nAdditionnal information:$reset_color " ; uname -a
  print -P "\n$FG[003]Users logged on:$reset_color " ; w -h
  print -P "\n$FG[003]Current date:$reset_color " ; date
  print -P "\n$FG[003]Machine stats:$reset_color " ; uptime
  print -P "\n$FG[003]Current network location:$reset_color " ; scselect
  print -P "\n$FG[003]Public facing IP Address:$reset_color " ; myip
  print -P "\n$FG[003]Local IP Address:$reset_color "; localip
  print -P "\n$FG[003]DNS Configuration:$reset_color " ; scutil --dns | sed -ne '/resolver #1/,$ p' | head -n +6
  print
}

#   ---------------------------------------
#   8.  WEB DEVELOPMENT
#   ---------------------------------------

httpHeaders () { /usr/bin/curl -I -L $@ ; }             # httpHeaders:      Grabs headers from web page




# Aliases from https://justin.abrah.ms/dotfiles/zsh.html

alias ping='ping -c 5'      # Pings with 5 packets, not unlimited
alias df='df -h'            # Disk free, in gigabytes, not bytes
alias du='du -h -c'         # Calculate total disk usage for a folder

# curl for useragents
alias iecurl="curl -H \"User-Agent: Mozilla/5.0 (Windows; U; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)\""
alias ffcurl="curl -H \"User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.0 (.NET CLR 3.5.30729)\""
