#!/usr/bin/env zsh

# Search youtube and play top result automatically with VLC in the background
yt-lucky() {
    URL=$(youtube-dl -j ytsearch1:$1 | jq '.webpage_url' | sed -e 's/^"//' -e 's/"$//')
    if [[ -n "$URL" ]]; then
        vlc $URL NUL &
    else
        echo "No URL found!"
    fi
}

# Play youtube url with VLC in the background
yt() {
    vlc $@ NUL &
}

# Dictionary search, prefix ^ to get only words starting letters. ex: ^wh
dict() {
    grep "$@" /usr/share/dict/words
}

# git clone, places repositories in my 'Gitbox' folder
ghget() {
    # input: rails/rails
    USER=$(echo $@ | tr "/" " " | awk '{print $1}')
    REPO=$(echo $@ | tr "/" " " | awk '{print $2}')
    mcd "$HOME/Gitbox/$USER" && \
    git clone "https://github.com/$@" && \
    cd $REPO
}

# Input podcast app url i.e https://podcasts.apple.com/us/podcast/the-daily/id1200361736
podrss() {
    ID=$(echo $1 | cut -d "/" -f7 | cut -c 3-)
    curl -s https://itunes.apple.com/lookup\?id\=$ID | jq ".results[0].feedUrl" | xargs echo
}
# Input channel url i.e https://www.youtube.com/channel/UCGYYNGmyhZ_kwBF_lqqXdAQ
ytrss() {
    ID=$(echo $1 | cut -d "/" -f5)
    NAME=$(wget -qO- $1 | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si')
    NAME=$(echo $NAME | xargs echo | rev | cut -c 11- | rev )
    NAME=$(ascii "$NAME")
    NAME=$(urlencode $NAME)
    echo "https://www.scriptbarrel.com/xml.cgi?channel_id=$ID&name=$NAME"
}

add-podcast() {
    FEED=$1
    if [[ "$FEED" == *"apple.com"* ]]; then
        FEED=$(podrss $FEED)
    fi
    echo $FEED >> ~/.newsboat/podcast
}

add-youtube() {
    echo $(ytrss $1) >> ~/.newsboat/youtube
}


alias urldecode='python -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python -c "import sys, urllib.parse as ul; print (ul.quote_plus(sys.argv[1]))"'

ascii() {
    echo "'$1'" | xargs python -c "import sys, string; s=''.join(sys.argv[1:]); print(''.join(list(filter(lambda x: x in string.printable, s))))"
}