#!/usr/bin/env zsh

# Ruby, rbenv
eval "$(rbenv init -)"

# Custom dropbox PATH environment
PATH="$HOME/Dropbox/.bin:$PATH"

# SqlPackage installation
PATH="$PATH:$HOME/Dropbox/.bin/sqlpackage"

export PATH

# NVM Setup
export NVM_DIR="$HOME/.nvm"
source $(brew --prefix nvm)/nvm.sh