#!/usr/bin/env zsh

# Ruby, rbenv
RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)"
eval "$(rbenv init -)"

# Python, pyenv
PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Custom dropbox PATH environment
PATH="$HOME/Dropbox/.bin:$PATH"

# SqlPackage installation
# PATH="$PATH:$HOME/Dropbox/.bin/sqlpackage"

# OpenVPN +
PATH=/usr/local/sbin:$PATH

# Add .NET Core SDK tools
# PATH="$PATH:$HOME/.dotnet/tools"

# NVM Setup
export NVM_DIR="$HOME/.nvm"
source $(brew --prefix nvm)/nvm.sh

# Android SDK and NDK Setup
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"

# GPG
export GPG_TTY=$(tty)

# dotnet SDK
# export MSBuildSDKsPath="/usr/local/opt/dotnet/libexec/sdk/$(dotnet --version)/Sdks"
# export DOTNET_ROOT="$HOMEBREW_PREFIX/opt/dotnet/libexec"
export DOTNET_ROOT="$HOME/.dotnet"
PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools"

# Fix Pupeteer Error
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`

export PATH