#!/usr/bin/env zsh

# Ruby, rbenv
eval "$(rbenv init -)"

# Python, pyenv
PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Custom dropbox PATH environment
PATH="$HOME/Dropbox/.bin:$PATH"

# SqlPackage installation
PATH="$PATH:$HOME/Dropbox/.bin/sqlpackage"

# OpenVPN +
PATH=/usr/local/sbin:$PATH

export PATH

# NVM Setup
export NVM_DIR="$HOME/.nvm"
source $(brew --prefix nvm)/nvm.sh

# Android SDK and NDK Setup
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"

# GPG
export GPG_TTY=$(tty)